### PR TITLE
Move finding of scopes into scope manager

### PR DESCRIPTION
**Pull request by AlexStansfield**
Maybe I'm barking up the wrong tree here, but let me know before I get too far down this path.

Basically we wanted to replace the Scope entity (so we can add extra field for referential integrity). We've already done it with the User and that was easy as you provide your own UserProvider and all is well. With scopes it wasn't so simple as the Client Manager and Scope storage both fetch scopes using the OAuth2ServerBundle:Scope repository. Meaning we'd have to extend/replace the scope storage and client manager if we wanted to use our own Scope entity.

All I've done here is have the Scope manager handle the two cases where you're fetching scopes. The manager service is passed into the Client Manager and the Scope storage.

I created a ScopeManagerInterface so anyone replacing the scope manager (like we wish to) can implement it to make sure they have the required methods.

This could also be done for Clients too.

### CODE REVIEW

**Comment by AlexStansfield** [comment]
hmm, well I successfully broke the build :/

**Comment by AlexStansfield** [comment]
Hurrah, tests fixed

**Comment by AlexStansfield** [comment]
Just wondered if there was news on this?

**Comment by bshaffer** [comment]
Hey, this looks great!

One request - rebase your branch so that your three commits are one. This will make the commit history for the main branch much cleaner, as we don't really want the commit that breaks the build as part of the develop branch. 

I'll merge it as soon as this is done.

**Comment by AlexStansfield** [comment]
Done :)

**Pull request merged**
